# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

  port: 8080
#  servlet:
#    context-path:

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev

  main:
    # logging can be turned off
    log-startup-info: false

  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  # 配置redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    timeout: 30000

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jinanluke.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      # 全局配置，数据库配置，逻辑删除配置
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


#分页插件
#pagehelper:
#  reasonable: true # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
#  support-methods-arguments: true
#  params: count= countSql
#  row-bounds-with-count: true
#  helper-dialect: mysql

#log
#logging:
#  config: classpath:logback-spring.xml
